/************************************************************
* @File Name          : Struct_RightFaxStatusRequest
* @Description        : 
* @Author             : AppShark Team
* @Created Date       : 
* @Last Updated Date  : 
**********************************************************/
public with sharing class Struct_RightFaxStatusRequest {
        
    public string RightFaxJobId {get;set;}
        
}