/************************************************************
* @File Name          : Struct_RightFaxStatusResponse
* @Description        : 
* @Author             : AppShark Team
* @Created Date       : 
* @Last Updated Date  : 
**********************************************************/
public class Struct_RightFaxStatusResponse {
    public string jobId {get;set;} 
    public string isSuccessful {get;set;} 
    public string status {get;set;} 
    public additionalProperties additionalProperties {get;set;} 
    public class additionalProperties{}     
}