/************************************************************
* @File Name          : Struct_Case360Response
* @Description        : 
* @Author             : AppShark Team
* @Created Date       : 
* @Last Updated Date  : 
**********************************************************/
public class Struct_Case360Response {
        public string salesForceDocumentId {get;set;} 
        public string case360DocumentId {get;set;} 
        public string isSuccess {get;set;} 
}